<!DOCTYPE html>
<html lang="en-us">

<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="chrome=1">
<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="referrer" content="no-referrer">
<meta name="description" content="Example blog">


    <meta property="twitter:site" content="@juliasilge">

<meta property="twitter:title" content="Ten Thousand Tweets">

    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:image" content="/img/banner.png">

<meta property="twitter:description" content="">

<title>


     Julia Silge - Ten Thousand Tweets 

</title>
<link rel="canonical" href="/blog/ten-thousand-tweets/">


<style media="screen">
  @font-face {
  font-family: 'Nexa Bold';
  src: url('/fonts/Nexa Bold.otf');
}

html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed,
figure, figcaption, footer, header, hgroup,
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
  margin: 0;
  padding: 0;
  border: 0;
  font-size: 100%;
  font: inherit;
  vertical-align: baseline;
}
/* HTML5 display-role reset for older browsers */
article, aside, details, figcaption, figure,
footer, header, hgroup, menu, nav, section {
  display: block;
}
body {
  line-height: 1;
}
ol, ul {
  list-style: none;
}
blockquote, q {
  quotes: none;
}
blockquote:before, blockquote:after,
q:before, q:after {
  content: '';
  content: none;
}
table {
  border-collapse: collapse;
  border-spacing: 0;
}

*,
*:before,
*:after {
  box-sizing: border-box;
}
a,
a:visited,
a:focus,
a:active {
  text-decoration: none;
}
html {
  height: 100%;
  font-size: 16px;
}
body {
  display: -webkit-flex;
  display: -moz-flex;
  display: -ms-flexbox;
  display: -ms-flex;
  display: flex;
  -webkit-flex-direction: column;
  -moz-flex-direction: column;
  -ms-flex-direction: column;
  flex-direction: column;
  -webkit-align-items: center;
  -moz-align-items: center;
  -ms-align-items: center;
  align-items: center;
  -webkit-justify-content: flex-start;
  -moz-justify-content: flex-start;
  -ms-justify-content: flex-start;
  justify-content: flex-start;
  width: 100%;
  min-height: 100%;
  font-weight: 400;
  font-family: 'Helvetica Neue', 'Arial', sans-serif;
  color: #111111;
  line-height: 1.6;
  text-rendering: optimizeLegibility !important;
}
.icon {
  text-rendering: geometricPrecision !important;
}
section {
  display: -webkit-flex;
  display: -moz-flex;
  display: -ms-flexbox;
  display: -ms-flex;
  display: flex;
  -webkit-justify-content: center;
  -moz-justify-content: center;
  -ms-justify-content: center;
  justify-content: center;
  -webkit-align-items: center;
  -moz-align-items: center;
  -ms-align-items: center;
  align-items: center;
  width: 100%;
}
.container {
  display: -webkit-flex;
  display: -moz-flex;
  display: -ms-flexbox;
  display: -ms-flex;
  display: flex;
  width: 100%;
}
section.header .container {
  -webkit-align-items: center;
  -moz-align-items: center;
  -ms-align-items: center;
  align-items: center;
  -webkit-justify-content: center;
  -moz-justify-content: center;
  -ms-justify-content: center;
  justify-content: center;
}
section.header .content {
  display: -webkit-flex;
  display: -moz-flex;
  display: -ms-flexbox;
  display: -ms-flex;
  display: flex;
  -webkit-flex-direction: column;
  -moz-flex-direction: column;
  -ms-flex-direction: column;
  flex-direction: column;
  -webkit-align-items: center;
  -moz-align-items: center;
  -ms-align-items: center;
  align-items: center;
}
section.header .container .logo {
  max-width: 100px;
  margin-left: -2em;
}
section.header .name {
  padding-top: 20px;
  font-size: 28px;
  font-family: 'Nexa Bold', 'Helvetica Neue', 'Arial', sans-serif;
  letter-spacing: -0.005rem;
  text-transform: uppercase;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  font-smoothing: antialiased;
  color: #333333;
  color: #555555;
}
section.header nav {
  margin-bottom: 16px;
}
section.header nav ul {
  list-style: none;
  text-align: center;
  display: -webkit-inline-flex;
  display: -moz-inline-flex;
  display: -ms-inline-flexbox;
  display: -ms-inline-flex;
  display: inline-flex;
}
section.header nav ul a {
  margin-left: 6px;
  margin-right: 6px;
}
section.header nav ul a:first-child {
  margin-left: 0;
}
section.header nav ul a:last-child {
  margin-right: 0;
}
section.header nav ul li {
  color: #555555;
  font-weight: 400;
  font-size: 14px;
  text-transform: uppercase;
  font-family: 'Helvetica Neue', 'Arial', sans-serif;
  -webkit-transition: color 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
  -moz-transition: color 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
  -ms-transition: color 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
  -o-transition: color 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
}
section.header nav ul li:hover {
  color: #111111;
}
section.footer .container {
  -webkit-align-items: center;
  -moz-align-items: center;
  -ms-align-items: center;
  align-items: center;
  -webkit-justify-content: center;
  -moz-justify-content: center;
  -ms-justify-content: center;
  justify-content: center;
  flex-direction: column-reverse;
  width: 100%;
  text-align: center;
}
section.footer .container a {
  font-size: 14px;
  margin-left: 6px;
  margin-right: 6px;
  opacity: 0.6;
  -webkit-transition: opacity 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
  -moz-transition: opacity 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
  -ms-transition: opacity 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
  -o-transition: opacity 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
}
section.footer .container a:first-child {
  margin-left: 0;
}
section.footer .container a:last-child {
  margin-right: 0;
}
section.footer .container a:hover {
  opacity: 0.8;
}
section.footer .container a .icon {
  width: 16px;
  height: 16px;
}
section.footer .container .copyright {
  flex-grow: 0.5;
  text-align: start;
}
section.footer .container .icons {
  flex-grow: 0.5;
  text-align: end;
}
section.main .container {
  -webkit-align-items: center;
  -moz-align-items: center;
  -ms-align-items: center;
  align-items: center;
  -webkit-justify-content: flex-start;
  -moz-justify-content: flex-start;
  -ms-justify-content: flex-start;
  justify-content: flex-start;
}
section.main .content {
  color: #111111;
  font-size: 16px;
}
section.main .content .title-container {
  display: -webkit-flex;
  display: -moz-flex;
  display: -ms-flexbox;
  display: -ms-flex;
  display: flex;
  -webkit-justify-content: space-between;
  -moz-justify-content: space-between;
  -ms-justify-content: space-between;
  justify-content: space-between;
}
section.main .content .posts {
  margin-bottom: 4em;
}
section.main .content .page-heading {
  font-size: 20px;
  font-weight: 700;
  font-family: 'Helvetica Neue', 'Arial', sans-serif;
  letter-spacing: -0.005rem;
  text-transform: uppercase;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  font-smoothing: antialiased;
  color: #333333;
  margin-bottom: 16px;
}
section.main .content .front-matter .page-heading {
  margin-bottom: 0;
}
section.main .content .front-matter .meta {
  font-size: 14px;
  color: #666666;
  display: -webkit-flex;
  display: -moz-flex;
  display: -ms-flexbox;
  display: -ms-flex;
  display: flex;
  margin-bottom: 32px;
}
section.main .content .front-matter .date,
section.main .content .front-matter .author,
section.main .content .front-matter .tags,
section.main .content .front-matter .word-count,
section.main .content .front-matter .reading-time .middot {
  display: none;
}
section.main .content .front-matter .middot {
  font-size: 6px;
  margin: 0 6px;
  display: inline;
  vertical-align: middle;
}
section.main .content .front-matter .middot:before {
  content: "•";
}
section.main .content .front-matter .tags ul {
  display: -webkit-flex;
  display: -moz-flex;
  display: -ms-flexbox;
  display: -ms-flex;
  display: flex;
  -webkit-flex-direction: row;
  -moz-flex-direction: row;
  -ms-flex-direction: row;
  flex-direction: row;
  -webkit-align-items: center;
  -moz-align-items: center;
  -ms-align-items: center;
  align-items: center;
}
section.main .content .front-matter .tags ul li {
  -webkit-transition: opacity 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
  -moz-transition: opacity 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
  -ms-transition: opacity 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
  -o-transition: opacity 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
}
section.main .content .front-matter .tags ul li:hover {
  opacity: 0.7;
}
section.main .content .front-matter .tags ul li a {
  color: #666666;
}
section.main .container.f04 {
  -webkit-justify-content: center;
  -moz-justify-content: center;
  -ms-justify-content: center;
  justify-content: center;
}
section.main .container.f04 .content {
  display: -webkit-flex;
  display: -moz-flex;
  display: -ms-flexbox;
  display: -ms-flex;
  display: flex;
  -webkit-flex-direction: column;
  -moz-flex-direction: column;
  -ms-flex-direction: column;
  flex-direction: column;
  -webkit-align-items: center;
  -moz-align-items: center;
  -ms-align-items: center;
  align-items: center;
}
section.main .container.f04 .content .num {
  margin: 30px 0px 30px 0;
  font-weight: 400;
  font-family: 'Helvetica Neue', 'Arial', sans-serif;
  font-size: 50px;
}
section.main .container.f04 .content .detail {
  margin-bottom: 40px;
}
section.main .container .content .groupby {
  margin-top: 1em;
  padding-left: 0.5em;
}
section.main .container .content .post-item {
  display: -webkit-flex;
  display: -moz-flex;
  display: -ms-flexbox;
  display: -ms-flex;
  display: flex;
  -webkit-align-items: center;
  -moz-align-items: center;
  -ms-align-items: center;
  align-items: center;
  display: list-item;
  list-style: disc inside;
}
section.main .container .content .post-item .meta {
  font-size: 14px;
  color: #666666;
  display: none;
  min-width: 100px;
}
section.main .container .content .see-more {
  font-style: italic;
  float: right;
  font-size: 0.9em;
  margin-top: 2em;
  color: #313537;
}
section.main .container .content .see-more:hover {
  color: #666;
}
section {
  padding: 0 16px;
}
section.header {
  padding-top: 10px;
}
section.header-home {
  padding-top: 36px;
}
section.main {
  padding-top: 32px;
}
section.main .container .content .post-item .meta {
    display: block;
}
section.main .container .content .post-item {
    display: flex;
    list-style: none;
}
a {
  color: #428bca;
  -webkit-transition: color 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
  -moz-transition: color 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
  -ms-transition: color 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
  -o-transition: color 0.1s cubic-bezier(0.47, 0, 0.75, 0.72);
}
a:hover {
  color: #2a6496;
}
img {
  max-width: 100%;
}
section.main .content {
    width: 100%;
}
section.main .content .markdown {
  font-size: 1.1em;
  line-height: 1.75em;
  color: #313537;
  font-family: serif;
  font-weight: 300;
}
section.main .content .markdown h1,
section.main .content .markdown h2,
section.main .content .markdown h3,
section.main .content .markdown h4,
section.main .content .markdown h5,
section.main .content .markdown h6 {
  font-size: 22px;
  font-family: 'Helvetica Neue', 'Arial', sans-serif;
  letter-spacing: -0.005rem;
  font-weight: 700;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  font-smoothing: antialiased;
  color: #333333;
  text-transform: none;
  margin-top: 1.75rem;
}
section.main .content .markdown h1 {
  font-size: 1.75rem;
  margin-bottom: 2rem;
}
section.main .content .markdown h2 {
  font-size: 1.5rem;
  margin-bottom: 1.5rem;
}
section.main .content .markdown h3 {
  font-size: 1em;
  margin-bottom: 1rem;
}
section.main .content .markdown h4,
section.main .content .markdown h5,
section.main .content .markdown h6 {
  font-size: 1rem;
  margin-bottom: 1rem;
  letter-spacing: none;
}
section.main .content .markdown code,
section.main .content .markdown pre {
  font-family: 'Menlo', monospace;
  font-size: 0.98rem;
  background-color: #f7f7f7;
}
section.main .content .markdown code {
  /* enclosed by single backtick (`) */
  padding: .15em .5em;
  border-radius: 2px;
}
section.main .content .markdown pre {
  /* Hugo specific: consider using the 'highlight' shortcode */
  display: block;
  margin-top: 1rem;
  margin-bottom: 2rem;
  padding: 1rem;
  line-height: 1.5em;
  white-space: pre;
  word-break: break-all;
  word-wrap: break-word;
}
@media (min-width: 769px) {
  section.main .content .markdown pre {
    width: 110%;
    margin-left: -4%;
  }
}
section.main .content .markdown pre code {
  /* enclosed by 4 backticks (````) */
  padding: 0;
  font-size: 0.9rem;
}
section.main .content .markdown a code {
  color: #428bca !important;
}
section.main .content .markdown a code:hover {
  text-decoration: underline;
}
section.main .content .markdown p {
  text-align: justify;
  margin-top: 0;
  margin-bottom: 1em;
}
section.main .content .markdown ul,
section.main .content .markdown ol,
section.main .content .markdown dl {
  margin-top: 1rem;
  margin-bottom: 2rem;
}
section.main .content .markdown dt {
  font-weight: bold;
}
section.main .content .markdown dd {
  margin-bottom: .5rem;
}
section.main .content .markdown ul {
  list-style-type: disc;
  list-style-position: outside;
  margin-bottom: 1.25rem;
}
section.main .content .markdown ol {
  list-style-type: decimal;
  margin-bottom: 1.25rem;
}
section.main .content .markdown li {
  margin-left: 2em;
}
section.main .content .markdown em {
  font-style: italic;
}
section.main .content .markdown strong {
  font-weight: 700;
}
section.main .content .markdown hr {
  position: relative;
  margin: 1.75rem 0;
  border: 0;
  border-top: 1px solid #808080;
  border-top: 1px solid #999999;
}
section.main .content .markdown abbr {
  font-size: 0.85rem;
  font-weight: bold;
  color: #666666;
  text-transform: uppercase;
}
section.main .content .markdown abbr[title] {
  cursor: help;
  border-bottom: 1px dotted #808080;
}
section.main .content .markdown blockquote {
  padding: .5rem 1rem;
  margin: .8rem 0;
  color: #7a7a7a;
  border-left: .25rem solid #e5e5e5;
}
section.main .content .markdown blockquote p:last-child {
  margin-bottom: 0;
}
section.main .content .markdown figure {
  width: 100%;
  background: #fff;
  margin-bottom: 1em;
}
section.main .content .markdown figure img {
  width: 100%;
  height: auto;
  max-width: 100%;
  display: block;
  position: static;
  margin: auto;
}
section.main .content .markdown table {
  margin-bottom: 1rem;
  width: 100%;
  border: 1px solid #e5e5e5;
  border-collapse: collapse;
}
section.main .content .markdown td,
section.main .content .markdown th {
  padding: .25rem .5rem;
  border: 1px solid #e5e5e5;
}
section.main .content .markdown tbody tr:nth-child(odd) td,
section.main .content .markdown tbody tr:nth-child(odd) th {
  background-color: #f7f7f7;
}
section.main .content .markdown .footnotes ol {
  list-style-type: decimal;
  margin-left: 16px;
}
section.main .content .markdown .footnotes li {
  list-style-type: unset;
}
section.main .content .markdown .footnote-ref {
  font-size: 0.7em;
}
section.main .content .navigation {
  display: -webkit-flex;
  display: -moz-flex;
  display: -ms-flexbox;
  display: -ms-flex;
  display: flex;
  -webkit-flex-direction: column;
  -moz-flex-direction: column;
  -ms-flex-direction: column;
  flex-direction: column;
  -webkit-align-items: center;
  -moz-align-items: center;
  -ms-align-items: center;
  align-items: center;
}
section.main .content .navigation div {
  display: -webkit-flex;
  display: -moz-flex;
  display: -ms-flexbox;
  display: -ms-flex;
  display: flex;
  -webkit-flex-direction: row;
  -moz-flex-direction: row;
  -ms-flex-direction: row;
  flex-direction: row;
  -webkit-align-items: center;
  -moz-align-items: center;
  -ms-align-items: center;
  align-items: center;
  margin-top: 1em;
}
section.main .content .navigation .icon {
  width: 16px;
  height: 16px;
}
section.main .content .navigation a {
  width: 250px;
  margin-left: 1em;
  text-align: center;
  font-style: italic;
  color: #313537;
}

/* Fonts */

.wf-raleway-n4-active body, 
.wf-raleway-n4-active section.header nav ul li,
.wf-raleway-n7-active section.main .content .page-heading,
.wf-raleway-n2-active section.main .container.f04 .content .num,
.wf-raleway-n7-active section.main .content .markdown h1,
.wf-raleway-n7-active section.main .content .markdown h2,
.wf-raleway-n7-active section.main .content .markdown h3,
.wf-raleway-n7-active section.main .content .markdown h4,
.wf-raleway-n7-active section.main .content .markdown h5,
.wf-raleway-n7-active section.main .content .markdown h6 {
  font-family: 'Raleway';
}

.wf-merriweather-n3-active section.main .content .markdown {
  font-family: 'Merriweather';
}

.wf-ubuntu-mono-n4-active section.main .content .markdown code,
.wf-ubuntu-mono-n4-active section.main .content .markdown pre {
  font-family: 'Ubuntu Mono';
}
</style>
<style media="(min-width: 600px)">
  body {
-webkit-justify-content: center;
-moz-justify-content: center;
-ms-justify-content: center;
justify-content: center;
}
.non-narrow.zero-top-spacing {
padding-top: 0 !important;
}
section {
padding: 0 16px;
margin-left: 100px;
margin-right: 100px;
max-width: 750px;
}
section.header {
background-color: transparent;
}
section.header .container {
-webkit-justify-content: flex-start;
-moz-justify-content: flex-start;
-ms-justify-content: flex-start;
justify-content: flex-start;
}
section.header .container .logo {
margin: 0;
}
section.header-home .container .logo {
max-width: 180px;
margin-left: 20px;
}
section.header-home .name-home {
padding-top: 30px;
font-size: 40px;
}
section.header-home nav ul li {
font-size: 18px;
}
section.header .content {
-webkit-align-items: flex-start;
-moz-align-items: flex-start;
-ms-align-items: flex-start;
align-items: flex-start;
}
section.header .name {
color: #333333;
}
section.header nav {
font-size: 14px;
margin-bottom: 0;
}
section.header nav ul {
text-align: left;
}
section.header nav ul li {
color: #666666;
}
section.header nav ul li:hover {
color: #333333;
}
section.footer {
background-color: transparent;
}
section.footer .container {
flex-direction: row;
}
section.footer .container a {
margin-left: 3px;
margin-right: 3px;
color: #666666;
}
section.footer .container a:hover {
color: #333333;
}
section.footer .container a .icon {
font-size: 18px;
}
section.footer .container a .icon.larger {
font-size: 20px;
}
section.main .content .front-matter .date,
section.main .content .front-matter .author,
section.main .content .front-matter .tags,
section.main .content .front-matter .word-count,
section.main .content .front-matter .reading-time .middot {
display: initial;
}
section.main .container.f04 {
-webkit-justify-content: flex-start;
-moz-justify-content: flex-start;
-ms-justify-content: flex-start;
justify-content: flex-start;
}
section.main .container.f04 .content {
-webkit-align-items: flex-start;
-moz-align-items: flex-start;
-ms-align-items: flex-start;
align-items: flex-start;
}
section.main .container.f04 .content .num {
margin: 0 0 10px 0;
font-size: 32px;
}
section.main .container.f04 .content .detail {
margin-bottom: 30px;
}
.container {
padding: 0 30px;
}
section.header {
padding-top: 60px;
padding-bottom: 60px;
}
section.footer {
padding-top: 30px;
padding-bottom: 60px;
}
section.main {
padding-top: 0;
}
section.main .container .content .post-item {
display: flex;
list-style: none;
padding-left: 1.5em;
}
section.main .container .content .post-item .meta {
display: block;
}
section.main.post {
padding-top: 60px;
padding-bottom: 60px;
}
section.main .content .markdown blockquote {
padding-right: 5rem;
padding-left: 1.25rem;
}
section.main .content .navigation {
-webkit-flex-direction: row;
-moz-flex-direction: row;
-ms-flex-direction: row;
flex-direction: row;
}
section.main .content .navigation div {
margin-top: 0em;
}
</style>
<style media="(min-width: 769px)">
  section.main .content .markdown figure {
width: 110%;
margin-left: -4%;
}
section.main .content .markdown img {
max-width: 110%;
width: 110%;
margin-left: -4%;
}
</style>

<noscript>
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,600,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Merriweather:300,300i,700,700i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700" rel="stylesheet">
</noscript>


  <style type="text/css" media="screen">
    .hljs{display:block;background:white;padding:0.5em;color:#333333;overflow-x:auto}.hljs-comment,.hljs-meta{color:#969896}.hljs-string,.hljs-variable,.hljs-template-variable,.hljs-strong,.hljs-emphasis,.hljs-quote{color:#df5000}.hljs-keyword,.hljs-selector-tag,.hljs-type{color:#a71d5d}.hljs-literal,.hljs-symbol,.hljs-bullet,.hljs-attribute{color:#0086b3}.hljs-section,.hljs-name{color:#63a35c}.hljs-tag{color:#333333}.hljs-title,.hljs-attr,.hljs-selector-id,.hljs-selector-class,.hljs-selector-attr,.hljs-selector-pseudo{color:#795da3}.hljs-addition{color:#55a532;background-color:#eaffea}.hljs-deletion{color:#bd2c00;background-color:#ffecec}.hljs-link{text-decoration:underline}
  </style>



  <style type="text/css" media="screen">
    .progressive{overflow:hidden;position:relative;background:#efefef}.progressive__img{width:100%;height:100%;position:absolute;-webkit-transform:translateZ(0);transform:translateZ(0)}.progressive--not-loaded{filter:blur(30px);-webkit-filter:blur(30px)}.progressive--is-loaded{filter:blur(20px);-webkit-filter:blur(20px);-webkit-animation:sharpen .5s both;animation:sharpen .5s both}@-webkit-keyframes sharpen{from{filter:blur(20px);-webkit-filter:blur(20px)}to{filter:blur(0);-webkit-filter:blur(0)}}@keyframes sharpen{from{filter:blur(20px);-webkit-filter:blur(20px)}to{filter:blur(0);-webkit-filter:blur(0)}}
  </style>







<link rel="shortcut icon"

    href="/_images/favicon.ico"

>




</head>


<body>


<section class="header">

    <div class="container">
        <a href="/"><img class="logo" src="/_images/avatar_green.png" alt="logo" /></a>
        <div class="content">
            <a href="/"><div class="name"><h1>Julia Silge</h1></div></a>
            <nav>
                <ul>
                    
                        <a href="/blog/"><li>Blog</li></a>
                    
                    
                        
                    
                        
                            
                        
                    
                    
                        
                            <a href="/about/"><li>about</li></a>
                        
                    
                        
                            <a href="/resume/"><li>resume</li></a>
                        
                    
                </ul>
            </nav>
        </div>
    </div>
</section>


<section class="main post non-narrow zero-top-spacing">
    <div class="container">
        <div class="content">
            <div class="front-matter">
                <div class="title-container">
                    <div class="page-heading">

    Ten Thousand Tweets

</div>

                </div>
                <div class="meta">
                    <div class="date" title="Tue Dec 8 2015 00:00:00 UTC">Dec 8, 2015</div>
                    
                        
                    
                    <div class="reading-time"><div class="middot"></div>14 minute read</div>
                    <div class="tags">
                        <ul>
                          
                            <div class="middot"></div>
                            <li><a href="/tags/rstats">rstats</a> </li>
                          
                        </ul>
                    </div>
                </div>
            </div>
            <div class="markdown">
                
    
    

<p>I started learning the statistical programming language R this past summer, and discovering Hadley Wickham&rsquo;s data visualization package <code>ggplot2</code> has been a joy and a revelation. When I think back to how I made all the plots for my astronomy dissertation in the early 2000s (COUGH <a href="http://www.astro.princeton.edu/~rhl/sm/">SUPERMONGO</a> COUGH), I feel a bit in awe of what <code>ggplot2</code> can do and how easy and, might I even say, delightful it is to use. I recently passed the 10,000 tweet mark at <a href="http://twitter.com/juliasilge">my personal Twitter account</a>, so in this blog post I am going to use <code>ggplot2</code> to analyze my Twitter archive. You can download your own Twitter archive by following <a href="https://support.twitter.com/articles/20170160">these directions</a>. When I planned this project, I was mentally prepared to parse JSON and such, but it turns out that when you download your own Twitter archive, one of the files is a lovely, neat CSV file with every tweet you&rsquo;ve ever tweeted. Handy!</p>

<p>First, I&rsquo;ll load the libraries that I need to make my plots and read in the data from the CSV file.</p>

<pre><code class="language-r">library(ggplot2)
library(lubridate)
library(scales)

tweets &lt;- read.csv(&quot;./tweets.csv&quot;, stringsAsFactors = FALSE)
</code></pre>

<p>The timestamp on each tweet is a string at this point, so let&rsquo;s use a function from the <code>lubridate</code> package to convert the timestamp to a date-time object. The timestamps are recorded in UTC, so to make more interpretable plots, we need to convert to a different time zone. I joined Twitter in 2008 when I lived in Connecticut, and in the intervening years I lived in Texas, and now in Utah. Not to mention all the times I traveled elsewhere! I don&rsquo;t have geotagging turned on for my tweets because that freaks me out somewhat, so I don&rsquo;t have any information for individual tweets to assign time zones to them on a case-by-case basis. For a rough estimate, let&rsquo;s just assign all tweets to the Central Time Zone, using another function from <code>lubridate</code>. If we needed to do a better job on this, we could divide my tweets up by when I moved between various time zones; this still wouldn&rsquo;t be perfect because of tweeting while traveling.</p>

<pre><code class="language-r">tweets$timestamp &lt;- ymd_hms(tweets$timestamp)
tweets$timestamp &lt;- with_tz(tweets$timestamp, &quot;America/Chicago&quot;)
</code></pre>

<p>Now for some graphs!</p>

<h2 id="tweets-by-year-month-and-day">Tweets by Year, Month, and Day</h2>

<p>First let&rsquo;s make a basic histogram showing the distribution of my tweets over time.</p>

<pre><code class="language-r">ggplot(data = tweets, aes(x = timestamp)) +
        geom_histogram(aes(fill = ..count..)) +
        theme(legend.position = &quot;none&quot;) +
        xlab(&quot;Time&quot;) + ylab(&quot;Number of tweets&quot;) + 
        scale_fill_gradient(low = &quot;midnightblue&quot;, high = &quot;aquamarine4&quot;)
</code></pre>

<p><figure class="progressive"><img class="progressive__img progressive--not-loaded" data-progressive="/figs/2015-12-07-Ten-Thousand-Tweets/unnamed-chunk-4-1.png" src="/figs/2015-12-07-Ten-Thousand-Tweets/low/unnamed-chunk-4-1.png" alt="center" /></p></figure>

<p>This is obvious to more experienced users, but it took me a while to figure out that when writing out code for a plot over multiple lines, the <code>+</code> needs to go on the end of the previous line, not at the beginning of the new line. Use an aesthetic with <code>fill = ..count..</code> in the call to <code>geom_histogram</code> to make the fill color of each histogram bin reflect that bin&rsquo;s height. You can see I hit my own personal peak Twitter sometime in late 2012.</p>

<p>Perhaps we&rsquo;d like to see how many tweets I&rsquo;ve tweeted each year. Use the <code>year()</code> function from <code>lubridate</code> on the x-axis of the histogram and specify the breaks of the histogram in the call to <code>geom_histogram</code>.</p>

<pre><code class="language-r">ggplot(data = tweets, aes(x = year(timestamp))) +
        geom_histogram(breaks = seq(2007.5, 2015.5, by =1), aes(fill = ..count..)) +
        theme(legend.position = &quot;none&quot;) +
        xlab(&quot;Time&quot;) + ylab(&quot;Number of tweets&quot;) + 
        scale_fill_gradient(low = &quot;midnightblue&quot;, high = &quot;aquamarine4&quot;)
</code></pre>

<p><figure class="progressive"><img class="progressive__img progressive--not-loaded" data-progressive="/figs/2015-12-07-Ten-Thousand-Tweets/unnamed-chunk-5-1.png" src="/figs/2015-12-07-Ten-Thousand-Tweets/low/unnamed-chunk-5-1.png" alt="center" /></p></figure>

<p>What does my tweeting pattern look like over the days of the week? We can take a similar approach and use the <code>wday()</code> function from <code>lubridate</code> and specify the breaks for the histogram.</p>

<pre><code class="language-r">ggplot(data = tweets, aes(x = wday(timestamp, label = TRUE))) +
        geom_histogram(breaks = seq(0.5, 7.5, by =1), aes(fill = ..count..)) +
        theme(legend.position = &quot;none&quot;) +
        xlab(&quot;Day of the Week&quot;) + ylab(&quot;Number of tweets&quot;) + 
        scale_fill_gradient(low = &quot;midnightblue&quot;, high = &quot;aquamarine4&quot;)
</code></pre>

<p><figure class="progressive"><img class="progressive__img progressive--not-loaded" data-progressive="/figs/2015-12-07-Ten-Thousand-Tweets/unnamed-chunk-6-1.png" src="/figs/2015-12-07-Ten-Thousand-Tweets/low/unnamed-chunk-6-1.png" alt="center" /></p></figure>

<p>I&rsquo;ve seen other analyses showing that people tweet less on the weekends. Also, what a big difference between Wednesday and Tuesday/Thursday! I want to do a statistical test and see if these are real effects. The appropriate test is a single sample chi-squared test (or goodness of fit test); this test will take the distribution of tweets by weekday and see if the distribution we have is consistent with a given hypothesis, to within random sampling error. For example, could we have gotten this distribution of tweets just by chance, or do I really tweet less on the weekends? This kind of test can be done with any kind of expected frequencies, but first let&rsquo;s compare against the hypothesis of equal expected frequencies, i.e. the hypothesis that I tweet at the same rate on all days and I got this distribution of tweets just by chance and random sampling.</p>

<pre><code class="language-r">chisq.test(table(wday(tweets$timestamp, label = TRUE)))
</code></pre>

<pre><code>## 
## 	Chi-squared test for given probabilities
## 
## data:  table(wday(tweets$timestamp, label = TRUE))
## X-squared = 193.77, df = 6, p-value &lt; 2.2e-16
</code></pre>

<p>The chi-squared test indicates that the distribution of my tweets is highly unlikely to be uniform; we can reject the null hypothesis (the hypothesis that I tweet at the same rate on all days) with a high degree of confidence. Can the distribution in tweets be explained only as a difference between weekday and weekend behavior? It looks like Monday through Thursday are higher than Friday through Sunday.</p>

<pre><code class="language-r">myTable &lt;- table(wday(tweets$timestamp, label = TRUE))
mean(myTable[c(2:5)])/mean(myTable[c(1,6,7)])
</code></pre>

<pre><code>## [1] 1.283351
</code></pre>

<p>The values for Monday through Thursday are 1.283 higher than the other days, on average, close to <sup>5</sup>&frasl;<sub>4</sub>. Let&rsquo;s see if the chi-squared test says that my pattern of tweets is consistent with tweeting 1.25 times as often (<sup>5</sup>&frasl;<sub>4</sub>) on Monday through Thursday as on Friday through Sunday.</p>

<pre><code class="language-r">chisq.test(table(wday(tweets$timestamp, label = TRUE)), p = c(4, 5, 5, 5, 5, 4, 4)/32)
</code></pre>

<pre><code>## 
## 	Chi-squared test for given probabilities
## 
## data:  table(wday(tweets$timestamp, label = TRUE))
## X-squared = 44.001, df = 6, p-value = 7.388e-08
</code></pre>

<p>The p-value here is still very low, so we can reject this simple hypothesis too. I would not have guessed that there was such a strong association between the days of the week and my tweeting patterns.</p>

<p>For the months of the year, there is yet another convenient function in <code>lubridate</code>, the <code>month()</code> function, to put into the histogram.</p>

<pre><code class="language-r">ggplot(data = tweets, aes(x = month(timestamp, label = TRUE))) +
        geom_histogram(aes(fill = ..count..)) +
        theme(legend.position = &quot;none&quot;) +
        xlab(&quot;Month&quot;) + ylab(&quot;Number of tweets&quot;) + 
        scale_fill_gradient(low = &quot;midnightblue&quot;, high = &quot;aquamarine4&quot;)
</code></pre>

<p><figure class="progressive"><img class="progressive__img progressive--not-loaded" data-progressive="/figs/2015-12-07-Ten-Thousand-Tweets/unnamed-chunk-10-1.png" src="/figs/2015-12-07-Ten-Thousand-Tweets/low/unnamed-chunk-10-1.png" alt="center" /></p></figure>

<p>This is a pretty interesting annual pattern; I would not have predicted all of this before looking at this histogram. The decrease in August and September makes sense as this is generally a very busy time of year both in the various jobs I&rsquo;ve had since 2008 and for my family. The decrease going into spring? I&rsquo;m not really sure. Let&rsquo;s do the chi-squared test again, just to make sure these are not due to random sampling.</p>

<pre><code class="language-r">chisq.test(table(month(tweets$timestamp, label = TRUE)))
</code></pre>

<pre><code>## 
## 	Chi-squared test for given probabilities
## 
## data:  table(month(tweets$timestamp, label = TRUE))
## X-squared = 77.42, df = 11, p-value = 4.645e-12
</code></pre>

<p>Again, the chi-squared test indicates that the distribution of tweets by month is highly unlikely to be uniform and we can reject the null hypothesis (the hypothesis that I tweet the same amount in each month) with a high degree of confidence.</p>

<h2 id="tweets-by-time-of-day-time-to-put-the-phone-down">Tweets by Time of Day: Time to Put the Phone Down?</h2>

<p>To see what time of day I tweet, we need to take the timestamp date-time objects and strip out all the year, month, etc. information and leave only the time information. After fiddling about with this for quite a while, I got this to work using the <code>trunc</code> function in base R. This next line of code was the most difficult part of this analysis for me.</p>

<pre><code class="language-r">tweets$timeonly &lt;- as.numeric(tweets$timestamp - trunc(tweets$timestamp, &quot;days&quot;))
</code></pre>

<p>I also found that for my earliest tweets, there was no meaningful time information recorded. A good number of my earliest tweets have real dates recorded but 00:00:00 UTC for the time. Let&rsquo;s find these tweets and set the new <code>timeonly</code> column to <code>NA</code> for them. How many of my tweets don&rsquo;t have real time information?</p>

<pre><code class="language-r">tweets[(minute(tweets$timestamp) == 0 &amp; second(tweets$timestamp) == 0),11] &lt;- NA
mean(is.na(tweets$timeonly))
</code></pre>

<pre><code>## [1] 0.2165262
</code></pre>

<p>It turns out it&rsquo;s about 21.7%, so for my tweets vs. time graph, we will actually have not-quite-10,000 tweets. To make the graph, let&rsquo;s convert the new <code>timeonly</code> column to a date-time object and make a histogram. We can use a scaling function from the <code>scales</code> library to scale and label the x-axis.</p>

<pre><code class="language-r">class(tweets$timeonly) &lt;- &quot;POSIXct&quot;
ggplot(data = tweets, aes(x = timeonly)) +
        geom_histogram(aes(fill = ..count..)) +
        theme(legend.position = &quot;none&quot;) +
        xlab(&quot;Time&quot;) + ylab(&quot;Number of tweets&quot;) + 
        scale_x_datetime(breaks = date_breaks(&quot;3 hours&quot;), 
                         labels = date_format(&quot;%H:00&quot;)) +
        scale_fill_gradient(low = &quot;midnightblue&quot;, high = &quot;aquamarine4&quot;)
</code></pre>

<p><figure class="progressive"><img class="progressive__img progressive--not-loaded" data-progressive="/figs/2015-12-07-Ten-Thousand-Tweets/unnamed-chunk-14-1.png" src="/figs/2015-12-07-Ten-Thousand-Tweets/low/unnamed-chunk-14-1.png" alt="center" /></p></figure>

<p>So there is when I tweet. I see mid-morning and mid-afternoon peaks, and a major peak after my kids go to bed. I was actually surprised to see any overnight tweets at all; I am far from an night owl. What might be going on there?</p>

<pre><code class="language-r">latenighttweets &lt;- tweets[(hour(tweets$timestamp) &lt; 6),]
ggplot(data = latenighttweets, aes(x = timestamp)) +
        geom_histogram(aes(fill = ..count..)) +
        theme(legend.position = &quot;none&quot;) +
        xlab(&quot;Time&quot;) + ylab(&quot;Number of tweets&quot;) + ggtitle(&quot;Late Night Tweets&quot;) +
        scale_fill_gradient(low = &quot;midnightblue&quot;, high = &quot;aquamarine4&quot;)
</code></pre>

<p><figure class="progressive"><img class="progressive__img progressive--not-loaded" data-progressive="/figs/2015-12-07-Ten-Thousand-Tweets/unnamed-chunk-15-1.png" src="/figs/2015-12-07-Ten-Thousand-Tweets/low/unnamed-chunk-15-1.png" alt="center" /></p></figure>

<p>What are these tweets? I am <em>never</em> awake in the middle of the night!</p>

<p><blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">4am here. 3yo has been awake since 1am, crying, coughing, demanding chocolate milk, waking up croupy baby when I finally get him to sleep.</p>&mdash; Julia Silge (@juliasilge) <a href="https://twitter.com/juliasilge/status/175899182127783936">March 3, 2012</a></blockquote>
<script async src="http://platform.twitter.com/widgets.js" charset="utf-8"></script></p>

<p>Oh&hellip;</p>

<p><blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">2am vomit! (Not me.) Motherhood is so GLAMOROUS sometimes&hellip;</p>&mdash; Julia Silge (@juliasilge) <a href="https://twitter.com/juliasilge/status/338576358059950080">May 26, 2013</a></blockquote>
<script async src="http://platform.twitter.com/widgets.js" charset="utf-8"></script></p>

<p>Hmmmm&hellip;</p>

<p>So it turns out that I have occasionally been up in the middle of the night. Not all these overnight tweets were related to small children and illness. Some were from times when I was traveling west to the Pacific Time Zone and were not actually as late as they appeared because of the way I assigned the time zone. And some were just from when I stayed up a bit late, of course! The tweets that came in peaks that you can see in the histogram were more likely to be episodes of sick little ones. I am so glad that my kids are older now and we are mostly past this stage of parenthood! You can see how the number of late night tweets (never large to start with) has decreased over the years I have been on Twitter.</p>

<h2 id="hashtag-retweet-me-bro">HASHTAG RETWEET ME, BRO</h2>

<p>Let&rsquo;s look at my usage of hashtags, retweets, and replies.</p>

<p><iframe src="http://giphy.com/embed/ub43ozIc6hXSE" width="360" height="360" frameBorder="0" class="giphy-embed"> </iframe>
<p><a href="http://giphy.com/gifs/jimmy-fallon-reaction-gif-hashtag-ub43ozIc6hXSE">via GIPHY</a></p></p>

<p>I can use regex and <code>grep</code> to find all the hashtags in my tweets. Let&rsquo;s see what fractions of my tweets have hashtags and look at that visually.</p>

<pre><code class="language-r">ggplot(tweets, aes(factor(grepl(&quot;#&quot;, tweets$text)))) +
        geom_bar(fill = &quot;midnightblue&quot;) + 
        theme(legend.position=&quot;none&quot;, axis.title.x = element_blank()) +
        ylab(&quot;Number of tweets&quot;) + 
        ggtitle(&quot;Tweets with Hashtags&quot;) +
        scale_x_discrete(labels=c(&quot;No hashtags&quot;, &quot;Tweets with hashtags&quot;))
</code></pre>

<p><figure class="progressive"><img class="progressive__img progressive--not-loaded" data-progressive="/figs/2015-12-07-Ten-Thousand-Tweets/unnamed-chunk-16-1.png" src="/figs/2015-12-07-Ten-Thousand-Tweets/low/unnamed-chunk-16-1.png" alt="center" /></p></figure>

<p>As I would have guessed, I am not a big user of hashtags; only 1.7% of my tweet have hashtags. Maybe #rstats and/or the process of trying to spread the word of my new professional blog will change my mind, but it is not very &ldquo;me&rdquo;. In fact, most of the tweets that <em>do</em> have hashtags and fall in the right bin in this graph are actually retweets of other people&rsquo;s tweets with whatever hashtags they used.</p>

<p>Speaking of retweets, one of the columns in the CSV file from Twitter codes whether the tweet is a retweet or not, so it is not tough to see how many tweets are retweeted vs. original content.</p>

<pre><code class="language-r">ggplot(tweets, aes(factor(!is.na(retweeted_status_id)))) +
        geom_bar(fill = &quot;midnightblue&quot;) + 
        theme(legend.position=&quot;none&quot;, axis.title.x = element_blank()) +
        ylab(&quot;Number of tweets&quot;) + 
        ggtitle(&quot;Retweeted Tweets&quot;) +
        scale_x_discrete(labels=c(&quot;Not retweeted&quot;, &quot;Retweeted tweets&quot;))
</code></pre>

<p><figure class="progressive"><img class="progressive__img progressive--not-loaded" data-progressive="/figs/2015-12-07-Ten-Thousand-Tweets/unnamed-chunk-17-1.png" src="/figs/2015-12-07-Ten-Thousand-Tweets/low/unnamed-chunk-17-1.png" alt="center" /></p></figure>

<p>Only 4.8% of my tweets are retweets of others. The <code>scale_x_discrete</code> function is a nice, useful thing for relabeling the levels of a categorical variable for plotting. Before I applied this function, the labels just said &ldquo;FALSE&rdquo; and &ldquo;TRUE&rdquo;.</p>

<p>I am not a huge user of hashtags or retweets; now let&rsquo;s look at my replying habits. There is another column in the CSV file that codes whether the tweet is in reply to another tweet.</p>

<pre><code class="language-r">ggplot(tweets, aes(factor(!is.na(in_reply_to_status_id)))) +
        geom_bar(fill = &quot;midnightblue&quot;) + 
        theme(legend.position=&quot;none&quot;, axis.title.x = element_blank()) +
        ylab(&quot;Number of tweets&quot;) + 
        ggtitle(&quot;Replied Tweets&quot;) +
        scale_x_discrete(labels=c(&quot;Not in reply&quot;, &quot;Replied tweets&quot;))
</code></pre>

<p><figure class="progressive"><img class="progressive__img progressive--not-loaded" data-progressive="/figs/2015-12-07-Ten-Thousand-Tweets/unnamed-chunk-18-1.png" src="/figs/2015-12-07-Ten-Thousand-Tweets/low/unnamed-chunk-18-1.png" alt="center" /></p></figure>

<p>So 26.1% of my tweets are in reply to another person&rsquo;s tweets, quite a bit higher than the other categories we&rsquo;ve looked at. I am a fairly social user of the social media, it appears.</p>

<p>Let&rsquo;s put these categories together and see if there have been changes in my patterns of tweeting over time. I&rsquo;ll make a new column that codes the &ldquo;type&rdquo; of the tweet: regular, RT, or reply. My approach here is to first assign all the tweets to the regular category, then go through and overwrite this type with RT or reply if appropriate. I want this to be a factor variable, and lastly I reorder the factor variable in the order I want.</p>

<pre><code class="language-r">tweets$type &lt;- &quot;tweet&quot;
tweets[(!is.na(tweets$retweeted_status_id)),12] &lt;- &quot;RT&quot;
tweets[(!is.na(tweets$in_reply_to_status_id)),12] &lt;- &quot;reply&quot;
tweets$type &lt;- as.factor(tweets$type)
tweets$type = factor(tweets$type,levels(tweets$type)[c(3,1,2)])
</code></pre>

<p>Let&rsquo;s look at how my habits in original tweeting, retweeting, and replying have changed over time.</p>

<pre><code class="language-r">ggplot(data = tweets, aes(x = timestamp, fill = type)) +
        geom_histogram() +
        xlab(&quot;Time&quot;) + ylab(&quot;Number of tweets&quot;) +
        scale_fill_manual(values = c(&quot;midnightblue&quot;, &quot;deepskyblue4&quot;, &quot;aquamarine3&quot;))
</code></pre>

<p><figure class="progressive"><img class="progressive__img progressive--not-loaded" data-progressive="/figs/2015-12-07-Ten-Thousand-Tweets/unnamed-chunk-20-1.png" src="/figs/2015-12-07-Ten-Thousand-Tweets/low/unnamed-chunk-20-1.png" alt="center" /></p></figure>

<p>Hmmmm, that is good, but it might be better to see this as a proportion of the total.</p>

<pre><code class="language-r">ggplot(data = tweets, aes(x = timestamp, fill = type)) +
        geom_bar(position = &quot;fill&quot;) +
        xlab(&quot;Time&quot;) + ylab(&quot;Proportion of tweets&quot;) +
        scale_fill_manual(values = c(&quot;midnightblue&quot;, &quot;deepskyblue4&quot;, &quot;aquamarine3&quot;))
</code></pre>

<p><figure class="progressive"><img class="progressive__img progressive--not-loaded" data-progressive="/figs/2015-12-07-Ten-Thousand-Tweets/unnamed-chunk-21-1.png" src="/figs/2015-12-07-Ten-Thousand-Tweets/low/unnamed-chunk-21-1.png" alt="center" /></p></figure>

<p>By changing to <code>position = &quot;fill&quot;</code> in a call to <code>geom_bar</code> we can see how the proportion of these categories has changed. This is not entirely a great measure here, because Twitter did not keep track of which tweets were retweeted or replied before sometime in 2010. Undoubtedly, some of my tweets in 2008 and 2009 were RTs and replies, but Twitter did not keep track of this officially for each tweet. Looking at the more recent years when these data <em>were</em> tracked, my proportion of retweets, replies, and original tweets looks mostly stable. This does mean that the estimates in the bar graphs above for reply and RT are biased low; estimating from the graph, those numbers may be up to twice as high.</p>

<h2 id="no-more-characters-for-you">No More Characters For You</h2>

<p>Lastly, let&rsquo;s look at the distribution of the number of characters in my tweets. I can use one of the functions from the <code>apply</code> family of functions to count up the characters in each tweet in my archive.</p>

<pre><code class="language-r">tweets$charsintweet &lt;- sapply(tweets$text, function(x) nchar(x))
</code></pre>

<p>Let&rsquo;s see what the distribution of character count looks like for my tweets.</p>

<pre><code class="language-r">ggplot(data = tweets, aes(x = charsintweet)) +
        geom_histogram(aes(fill = ..count..), binwidth = 8) +
        theme(legend.position = &quot;none&quot;) +
        xlab(&quot;Characters per Tweet&quot;) + ylab(&quot;Number of tweets&quot;) + 
        scale_fill_gradient(low = &quot;midnightblue&quot;, high = &quot;aquamarine4&quot;)
</code></pre>

<p><figure class="progressive"><img class="progressive__img progressive--not-loaded" data-progressive="/figs/2015-12-07-Ten-Thousand-Tweets/unnamed-chunk-23-1.png" src="/figs/2015-12-07-Ten-Thousand-Tweets/low/unnamed-chunk-23-1.png" alt="center" /></p></figure>

<p>So that is fairly interesting. I am more likely to use many or most of those precious 140 characters allowed on Twitter than to go for brevity. BUT WAIT! What are those tweets with MORE than 140 characters?!? What magic have I worked? I can find these tweets by indexing the data frame using <code>tweets[(tweets$charsintweet &gt; 140),]</code>. After looking through them, it turns out that they are all tweets that use special characters and certain special punctuation and the like. The CSV file that I downloaded from Twitter uses special extra punctuation to make sure it is clear what is going on in these situations. Here is an example tweet that has a bunch of these special characters:</p>

<pre><code class="language-r">tweets[(tweets$tweet_id == 182267407480528896),'text']
</code></pre>

<pre><code>## [1] &quot;Gave 6mo baby soft-cooked egg yolk &amp;amp; sweet potato tonight. \&quot;He looks good in orange,\&quot; says @DoctorMac. \&quot;Brings out the blue in his eyes.\&quot;&quot;
</code></pre>

<p>This means that my histogram above is biased high a little bit; the number of characters per tweet is actually slightly lower than shown there. If I needed to, I could use regex and count each <code>&amp;amp;</code> only once and so forth. Or I could use the number of tweets that have greater than 140 characters to correct for this effect, or the number of tweets that contain special characters at a given character count, or some similar strategy, if it was important that I know the number of characters per tweet to this level of precision. I am happy with this current estimate of my character usage for my purposes right now.</p>

<p>The tweets with really low numbers of characters made me a bit suspicious too, but it turns out they are all real and normal tweets. Many were just very short replies to other people, but sometimes it turns out you don&rsquo;t need many characters to say what you want to say.</p>

<p><blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">Naps are awesome.</p>&mdash; Julia Silge (@juliasilge) <a href="https://twitter.com/juliasilge/status/1001102261">November 11, 2008</a></blockquote>
<script async src="http://platform.twitter.com/widgets.js" charset="utf-8"></script></p>

<p>So true.</p>

<p><blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">UGH, CANDY.</p>&mdash; Julia Silge (@juliasilge) <a href="https://twitter.com/juliasilge/status/528385670197567488">November 1, 2014</a></blockquote>
<script async src="http://platform.twitter.com/widgets.js" charset="utf-8"></script></p>

<p>Amen.</p>

<h2 id="the-end">The End</h2>

<p>So there are some examples of how to make histograms and bar charts using <code>ggplot2</code>, and do a bit of related analysis. The R Markdown file used to make this blog post is available <a href="https://github.com/juliasilge/juliasilge.github.io/blob/master/_R/2015-12-07-Ten-Thousand-Tweets.Rmd">here</a>. I am happy to hear feedback and suggestions as I am very much still learning about how to use R!</p>


                <br>
            </div>
            
                <div class="navigation">
                    
                    <div style="width: 100%;"></div>
                    
                    <div>
                        <a href="/blog/joy-to-the-world/">Joy to the World, and also Anticipation, Disgust, Surprise...</a>
                        <img class="icon" src="/img/next.svg" alt="next" />
                    </div>
                    
                </div>
            
            <br>
            <div class="disqus">
                <div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = 'datascienceish';
    var disqus_identifier = '\/blog\/ten-thousand-tweets\/';
    var disqus_title = 'Ten Thousand Tweets';
    var disqus_url = '\/blog\/ten-thousand-tweets\/';

    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
            </div>
        </div>
    </div>
</section>

<section class="footer">
    <div class="container">
        <div class="copyright">

        
            <a href="/license">Copyright © 2017 Julia Silge</a>
        

        </div>
        <div class="icons">

        
            <a href="https://github.com/juliasilge" target="_blank">
                <img class="icon" src="/img/github.svg" alt="github" />
            </a>
        

        
            <a href="https://twitter.com/juliasilge" target="_blank">
                <img class="icon" src="/img/twitter.svg" alt="twitter" />
            </a>
        

        
            <a href="https://www.linkedin.com/in/juliasilge" target="_blank">
                <img class="icon" src="/img/linkedin.svg" alt="linkedin" />
            </a>
        

        

        
            <a href="/index.xml">
                <img class="icon" src="/img/rss.svg" alt="rss" />
            </a>
        

        </div>
    </div>
</section>

<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
<script>
  WebFont.load({
    google: {
      families: ['Raleway:400,600,700', 'Merriweather:300,300i,700,700i', 'Ubuntu+Mono:400,700']
    }
  });
</script>

<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?...">
</script>

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
});
</script>


  <script src="/js/highlight.min.js" defer></script>
  



  <script src="/js/progressively.min.js" defer></script>



<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-68765210-1', 'auto');
ga('send', 'pageview');
</script>
<script async src='//www.google-analytics.com/analytics.js'></script>


<script>
  window.onload = function() {
    
      hljs.initHighlighting();
    
    
      progressively.init({delay: 30, throttle: 50});
    
  };
</script>


</body>
</html>

